name: Run Tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install numpy pandas

      - name: Run tests
        run: |
          cd DigitalNumbers
          python tests/chapter2_linear_systems/test_naive_gaussian_elimination.py
          python tests/chapter2_linear_systems/test_gaussian_elimination_PP.py
          python tests/chapter2_linear_systems/test_gaussian_elimination_TP.py
